Piece.create!([
  {name: "le streghe"},
  {name: "moses fantasie paganini"},
  {name: "bazzini la ronde des lutins"},
  {name: "sevcik air hongrois"}
])
Passage.create!([
  {description: " 1st variation with 16 bowing styles", title: "passage", piece_id: 1, endbar: "16", beginbar: "1", myscore: nil},
  {description: " by pressing the middle string with the bow harder on the middle string near the bridge the strings sound simultaneously", title: "passage", piece_id: 1, endbar: "18", beginbar: "17", myscore: nil},
  {description: "Ercreises forthe pizzicato.\nAtthe pizzicato pass the finger with\nmuch skin over the string, form the\nright corner of the nail to the left,\nwithout pressing strougly. The left\narm you may bend a little to te left.\n‘The string is tugged with the finger\nin trackets,\n", title: "II variation", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 16-51-22.png"},
  {description: "*) Touch the string near the point\nof the bow in such a way that the\ntones resemble the pizzicato.\n\n*%) At those arco-tones the stri\nis to be touched strougly with the\nfront part of the 4th or 3rd quarter\nof the bow so, that the touched to-\nnes resemble the pizzicato.\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-15-16.png"},
  {description: "*) Touch the string near the point\nof the bow in such a way that the\ntones resemble the pizzicato.\n\n*%) At those arco-tones the stri\nis to be touched strougly with the\nfront part of the 4th or 3rd quarter\nof the bow so, that the touched to-\nnes resemble the pizzicato.\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-15-16.png"},
  {description: "*) The passing frome one string to\nthe other has to be done with the\nelbow. On the countrary the fastto-\nnes on one string have to be played\nfrom the wrist.\n", title: "passage", piece_id: 1, endbar: "17", beginbar: "21", myscore: "Capture d’écran du 2025-11-23 17-16-52.png"},
  {description: "So.\nwith 10 bowings\n", title: "double croche lento", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-18-23.png"},
  {description: "The flageolets of the IIT™\nvariation may be executed\nin any way of the 4 kinds.\n", title: "variation III", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-20-11.png"},
  {description: "Exercises for the III! |\nvariation. =\n", title: "variation III", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-20-58.png"},
  {description: "2 flageolet double - stops\nalternately.\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-21-59.png"},
  {description: "Interv.\n\n41-416\n\nlon\n", title: "finale ", piece_id: 1, endbar: "1", beginbar: "16", myscore: "Capture d’écran du 2025-11-23 17-22-53.png"},
  {description: "*)The flageolet tones to\nbe held.\n", title: "finale", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-23-15.png"},
  {description: "by 5 notes\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-24-03.png"},
  {description: "on quavers with 12 styles\nof bowing\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-24-27.png"},
  {description: "on quavers with 11 exercises\nfor the right wrist.\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-25-03.png"},
  {description: "with 9 bowings,\n", title: "passage", piece_id: 1, endbar: "21", beginbar: "23", myscore: "Capture d’écran du 2025-11-23 17-25-56.png"},
  {description: "another rhythm with 7 styles\nof bowing\n2\n\n", title: "passage", piece_id: 1, endbar: "21", beginbar: "22", myscore: "Capture d’écran du 2025-11-23 17-26-26.png"},
  {description: "The 5 concluding bars\nvaried.\nCovered octaves.\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-27-47.png"},
  {description: "The same with fingering\n“octaves.\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-28-42.png"},
  {description: "*) To facilitate reading\nthe preparatory exerci-\nses for the introduction\n\nare noted in % measure.\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-29-33.png"},
  {description: "“)When gliding up the 4st\nfinger presses the string\nto the flageolet.\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-33-22.png"},
  {description: "from the I** variation with\n1ustyles of bowing.\n\nrad\n", title: "passage", piece_id: 1, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-33-52.png"},
  {description: "On eights with 14 styles\nof bowing.\n", title: "passage", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-35-11.png"},
  {description: "*) without flageolet.\n++) While gliding press\nthe string strougly with\nthe third finger.\n", title: "intervalle cadenz", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-36-47.png"},
  {description: "with 11. bowing styles.\n", title: "passage", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-37-39.png"},
  {description: "Preparation for the repe-\ntition of the introduction\nin flageolet tones.\nBounds in flageolets over\n23,44, and several positi -\nons.The leading 8 bars of\nthe introduction should be\nplayed in flageolets when\nrepeated. To perform those\nplainly, especially when\nchanging the high positi-\nons, the gliding in flageo-\nlets should be practised\nas follows:\n", title: "cadenz", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-38-01.png"},
  {description: "From the 5th position tohigher\n\n", title: "passage", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-39-06.png"},
  {description: "*\n*)\n~)\n*»\n\nfrom the 4th position.\nfrom the 3rd position.\nfrom the 2nd position.\nfrom the 1st position.\nfrom the open string.\n", title: "passage", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-39-27.png"},
  {description: "by 5 tones\n", title: "analyse", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-40-49.png"},
  {description: "with 13 bowings\n", title: "passage", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-41-27.png"},
  {description: "from the Ist variation\nwith 20 styles of bowing.\n", title: "passage", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-42-03.png"},
  {description: "Viotti's stroke. Paganini’s stroke.\n", title: "passage", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-42-30.png"},
  {description: "Paganini s stroke.\n\n(Triplet stroke on semi-\nquavers or on quavers.)\n", title: "variation III", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-43-20.png"},
  {description: "The ponticello is to be\nexecuted near the brid-\nge with the topmost third\nof the bow without pres-\nsing much (mp, mf) .To\nremain with the bow nea\nthe bridge one has to ma\nnage it a little forward\nand not parallel with the\nbridge.\n", title: "passage", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-43-46.png"},
  {description: "+) Count the quarters a-\nloud or make each step\ncoincide with each quarter.\n++) The bow is not to be\n\na lifted.\n", title: "passage", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-44-39.png"},
  {description: "*)When using the appog-\ngiatura the flageoletto-\nne turns out well also\nin fast tempo.\n", title: "passage", piece_id: 2, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-45-52.png"},
  {description: "“)When gliding up the 4st\nfinger presses the string\nto the flageolet.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-33-22.png"},
  {description: "Bars between two double\nbar lines are to be repea-\nted several times.\n\n; moll,\n\n60\nWithout sautillé and rico-\nchet.\n\n*) Bow not to be lifted.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-49-55.png"},
  {description: "Preparatory exercise for the rebounding bow (Ricochet). After striking the string with the point of the bow (fig.a) the bow re-\nbounds and bya small turn of the hand,is put into a vertical position (fig.b ),in order to strike the string again. The bow should be\nheld easily between the fingers to facilitate rebounding. The strokes should succeed each other regularly:\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-51-08.png"},
  {description: "‘With sautillé and ricochet.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-51-37.png"},
  {description: "The strokes accelerated and\nthe distance of rebounding\nreduced.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-52-06.png"},
  {description: "Two, three and four notes\nrebounding at one stroke.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-52-57.png"},
  {description: "*) Before the ricochet lift bow\n\nbefore the détaché **)bowre-\nmains on the string.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-53-30.png"},
  {description: "Ricochet alternates with\nsautillé.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-53-51.png"},
  {description: "+) Lest the bow stops re -\n\nbounding during a long suc-\n\ncession of tones, it is neces-\nsary to strike with the full\n\nbreadth of hair and also to\npass thus to the next string.\n‘The wrist remains bent al-\nso when approaching the\n\nmiddle of the bow.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 17-54-58.png"},
  {description: "*) Thumb slides along.\nag\n\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-05-51.png"},
  {description: "+) The pinching fingers are\nin brackets.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-06-53.png"},
  {description: nil, title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: nil},
  {description: "Pizzicato ) with fingering a) d)c)\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-07-25.png"},
  {description: "Tenths.\n2nd and st fingers\nnot to be lifted.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-08-02.png"},
  {description: "Minor thirds in flageo-\nlet double-stoppings.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-08-32.png"},
  {description: "+) Bow still strikes the\nstring with the point. The\ntones stroken should resem-\nble the pinched ones and\nsound as the latter.To a-\nvoid the fingers from get-\nting blisters, one should\nnot much press in pinching\nand use possibly the whole\njoint of the finger.\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-09-24.png"},
  {description: "+) The bow is held as in\nplaying.\n\nr= with the right hand.\nZ- with the leit hand.\n\n—\n", title: "passage", piece_id: 3, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-10-12.png"},
  {description: "Stops in connexion.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-11-27.png"},
  {description: ".) Lower note pizz.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-12-27.png"},
  {description: "+) Inthe bars 57, 59,€1 of\nthe original violin voice\nthere is always set Des in-\nstead of D due to an over-\nsight of the composer.\n\n++) Sink and lift the elbow\nwith unmoved wrist. With\nlittle bow. Bow remains\non the string.\n\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-12-48.png"},
  {description: "Triplets with various bo-\n\nwings.\nings ee\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-13-15.png"},
  {description: "*) The fingering in the\noriginal passage remains\nthe same as in the small\n\ngroups\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-14-08.png"},
  {description: "*) First détaché.\n+) In both bars first the\nlower voice, than the up-\nper voice and both voi-\nces together.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-14-37.png"},
  {description: "*) Move both fingers si-\nmultaneously to the tenth\nand place them for the dou-\nble stop.\n\nFirst practise détaché,\n\nPassage in triplets bar\n228-250 with 11bowings.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-15-20.png"},
  {description: "Passage in triplets bar\n253-270 with 8 bowings.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-15-51.png"},
  {description: "Melody in G major Can-\ntabile.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-16-10.png"},
  {description: "Bar 287- 800 in diffe-\nrent phrasing. 5\n", title: "passage diffirent phrasing meme nuance", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-17-08.png"},
  {description: "7\nFinal passage in double\nchords and common chords.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-18-04.png"},
  {description: "The scherzo theme in\ndouble stops.\n- © stops gs\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-18-38.png"},
  {description: "Bars between two double\nbar lines are to be repea-\nted several times.\n\nIntervals and changes of\nposition.\n", title: "viextemps concerto 2", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-19-20.png"},
  {description: "Division of chords with\nfingerings a.) 5.) c.)\n", title: "passage avec des noires", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-19-53.png"},
  {description: "Preparation for the chro-\nmatical succession of tones.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-20-29.png"},
  {description: "Chromatical succession of\ntones in various groups.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-21-00.png"},
  {description: "Analysis of double-stops.\n", title: "passage fingered tremolo", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-21-58.png"},
  {description: "Studies of independence\nof the fingers.\n", title: "passage, plusieurs voix", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-23-48.png"},
  {description: "Bowing styles for plian-\ncy of bowing on two\nstrings alternatel\n\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-24-37.png"},
  {description: "Arpeggi on 8 strings.\nWith 22 bowing styles.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-27-42.png"},
  {description: "Nuance on the G string.\n", title: "passage", piece_id: 4, endbar: "", beginbar: "", myscore: "Capture d’écran du 2025-11-23 18-28-05.png"}
])
